name: nimble_charts_common
version: 0.3.0-beta
description: Charts for Dart. A fork of charts_common
homepage: https://github.com/Nimblesite/nimble_charts

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.14.5
  intl: ^0.19.0
  logging: ^1.0.2
  meta: ^1.1.1
  vector_math: ^2.0.8

dev_dependencies:
  austerity: ^1.2.0
  build_runner: ^2.4.12
  mockito: ^5.4.4
  test: ^1.5.3
