name: build_and_test
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.2"
          channel: "stable"
          architecture: x64

      - name: Get Dependencies
        run: |
          for dir in charts_common charts_flutter charts_flutter/example; do
            cd $dir
            flutter pub get
            cd $GITHUB_WORKSPACE
          done

      - name: Analyze
        run: |
          for dir in charts_common charts_flutter charts_flutter/example; do
            cd $dir
            dart analyze --no-fatal-warnings
            cd $GITHUB_WORKSPACE
          done

      - name: Check Formatting
        run: |
          for dir in charts_common charts_flutter charts_flutter/example; do
            cd $dir
            dart format lib test --set-exit-if-changed
            cd $GITHUB_WORKSPACE
          done

      - name: Run Common Tests
        run: |
          cd charts_common
          flutter test --coverage
          cd $GITHUB_WORKSPACE

      - name: Run UI Tests
        run: |
          cd charts_flutter
          flutter test --coverage

      - name: Check Test Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: 'charts_flutter/coverage/lcov.info'
          min_coverage: 44.4